#pragma once

// Creation default and a one-line description for every _sofbuddy_* cvar.
// Names are strcmp-sorted so CvarLookup can binary-search. Defaults match
// the Buddy_GetEngineCvar / Bind() call in the owning feature. Gauges Bind
// as "0".

struct CvarInfo {
    const char* name;
    const char* def;
    const char* desc;
};

static const CvarInfo kCvarInfo[] = {
    {"_sofbuddy_cbuf_insert", "1", "shift the command buffer in place"},
    {"_sofbuddy_cbuf_insert_bytes", "0", "bytes shifted in place"},
    {"_sofbuddy_cbuf_insert_max", "0", "peak buffer size seen"},
    {"_sofbuddy_cbuf_insert_slow", "0", "times the fast path fell back"},
    {"_sofbuddy_cbuf_insert_us", "0", "time spent in the fast path"},
    {"_sofbuddy_cbuf_inserts", "0", "fast-path inserts served"},
    {"_sofbuddy_clamp_avg", "0", "mean ms deleted per highclamp"},
    {"_sofbuddy_clamp_broadcast_interval", "30", "seconds between lag broadcasts"},
    {"_sofbuddy_clamp_broadcast_ms", "0", "tell players when avg clamp hits this"},
    {"_sofbuddy_clamp_last", "0", "ms deleted by the last highclamp"},
    {"_sofbuddy_clamp_log_file", "0", "append clamps to sof_buddy-highclamps.txt"},
    {"_sofbuddy_clamp_lost_ms", "0", "total ms dropped by highclamps"},
    {"_sofbuddy_clamp_notify_ms", "0", "log a clamp that drops at least this"},
    {"_sofbuddy_clamp_window", "2", "seconds in the clamp average"},
    {"_sofbuddy_clsv", "1", "stufftext pipe to clients"},
    {"_sofbuddy_clsv_ack_wait_ms", "10000", "ms to wait for a client ack"},
    {"_sofbuddy_clsv_auto", "1", "send pipe chunks without a command"},
    {"_sofbuddy_clsv_chunk", "200", "max escaped bytes per chunk"},
    {"_sofbuddy_clsv_errors", "0", "pipe send failures"},
    {"_sofbuddy_clsv_interval", "1", "frames between pipe sends"},
    {"_sofbuddy_clsv_jobs", "0", "pipe jobs queued"},
    {"_sofbuddy_clsv_lanes", "4", "parallel client lanes"},
    {"_sofbuddy_clsv_per_tick", "2", "chunks sent per tick"},
    {"_sofbuddy_clsv_sent", "0", "pipe chunks delivered"},
    {"_sofbuddy_cmdcost", "1", "time console command handlers"},
    {"_sofbuddy_cmdcost_ema", "0", "highest per-name average ms"},
    {"_sofbuddy_cmdcost_ema_name", "0", "command with that average"},
    {"_sofbuddy_cmdcost_max", "0", "worst single handler sample ms"},
    {"_sofbuddy_cmdcost_n", "0", "samples of the last named command"},
    {"_sofbuddy_cmdcost_name", "0", "command that set the worst sample"},
    {"_sofbuddy_cmdpark", "1", "park console text near the tick"},
    {"_sofbuddy_cmdpark_cbuf_cursize", "0", "command buffer bytes in use"},
    {"_sofbuddy_cmdpark_cbuf_fill_max", "0", "peak command buffer bytes"},
    {"_sofbuddy_cmdpark_cbuf_last", "0", "last command-buffer drain ms"},
    {"_sofbuddy_cmdpark_cbuf_max", "0", "worst command-buffer drain ms"},
    {"_sofbuddy_cmdpark_defers", "0", "queues moved aside before the tick"},
    {"_sofbuddy_cmdpark_reserve_ms", "0", "park when the tick is this close"},
    {"_sofbuddy_cmdpark_strict", "1", "run console text after the tick"},
    {"_sofbuddy_cpuopt", "1", "master switch for cpu optimizations"},
    {"_sofbuddy_custom_respawn", "1", "CTF spawn away from enemies"},
    {"_sofbuddy_example_enabled", "1", "template feature switch"},
    {"_sofbuddy_hashmap", "1", "hash maps for cvar and command lists"},
    {"_sofbuddy_highclamps", "0", "ticks that dropped overrun time"},
    {"_sofbuddy_lagometer_enable", "1", "offer the lagometer minigame"},
    {"_sofbuddy_lagometer_warmup_frames", "200", "ticks skipped after a map change"},
    {"_sofbuddy_lowclamp_checks", "0", "tick decisions observed"},
    {"_sofbuddy_lowclamp_debug", "1", "log lowclamp clock jumps"},
    {"_sofbuddy_lowclamp_gained_ms", "0", "ms invented by lowclamps"},
    {"_sofbuddy_lowclamp_worst", "0", "worst single lowclamp jump ms"},
    {"_sofbuddy_lowclamps", "0", "clock jumps of a tick or more"},
    {"_sofbuddy_minigames_bg", "0", "0 tile backdrop, 1 solid panel"},
    {"_sofbuddy_minigames_enable", "1", "minigame tab and dot commands"},
    {"_sofbuddy_pipe_dl", "0", "unlock client downloads over the pipe"},
    {"_sofbuddy_pipe_dl_allowed", "0", "downloads the pipe has allowed"},
    {"_sofbuddy_printguard_broadcast_max", "999", "max chars in a broadcast print"},
    {"_sofbuddy_printguard_client_max", "1000", "max chars in a client print"},
    {"_sofbuddy_profiles", "1", "keep a guid on team_red_blue"},
    {"_sofbuddy_profiles_errors", "0", "profile push or lookup failures"},
    {"_sofbuddy_profiles_registered", "0", "profiles stored"},
    {"_sofbuddy_profiles_slots", "0", "slots currently signed in"},
    {"_sofbuddy_profiles_stufftext", "1", "re-push a lost guid via stufftext"},
    {"_sofbuddy_qpc", "1", "use a high-resolution timer"},
    {"_sofbuddy_recvbuf_applied", "0", "socket receive buffer actually set"},
    {"_sofbuddy_recvbuf_kb", "3107", "requested UDP receive buffer KiB"},
    {"_sofbuddy_recvbuf_sockets", "0", "sockets whose buffer was raised"},
    {"_sofbuddy_reldef", "1", "queue reliable messages to clients"},
    {"_sofbuddy_reldef_capture_bytes", "0", "bytes held in this frame"},
    {"_sofbuddy_reldef_dripped", "0", "queued parcels sent"},
    {"_sofbuddy_reldef_dropped", "0", "reliable writes dropped"},
    {"_sofbuddy_reldef_frame_first", "1", "snapshots jump ahead of big prints"},
    {"_sofbuddy_reldef_frame_reserve", "0", "packet bytes kept for snapshots"},
    {"_sofbuddy_reldef_max_drip_wait", "10", "ticks a parcel waits before send"},
    {"_sofbuddy_reldef_max_queue", "32", "parcels queued per player"},
    {"_sofbuddy_reldef_max_queue_bytes", "262144", "queued bytes per player"},
    {"_sofbuddy_reldef_oldest_wait", "0", "longest current parcel wait ticks"},
    {"_sofbuddy_reldef_one_per_tick", "0", "force every write through the queue"},
    {"_sofbuddy_reldef_queued", "0", "parcels queued since boot"},
    {"_sofbuddy_reldef_reserve", "256", "bytes kept free in the reliable buffer"},
    {"_sofbuddy_strict_exit", "0", "quit instead of logging a strict breach"},
    {"_sofbuddy_stufftext", "1", "server command to stuff client text"},
    {"_sofbuddy_stufftext_errors", "0", "stufftext sends that failed"},
    {"_sofbuddy_stufftext_sent", "0", "stufftext messages sent"},
    {"_sofbuddy_tickpace", "1", "wake the server on the 100 ms tick"},
    {"_sofbuddy_tickpace_late_avg", "0", "mean ms a tick ran late"},
    {"_sofbuddy_tickpace_saved", "0", "ticks caught before the next sleep"},
    {"_sofbuddy_tickpace_settle", "1", "credit time when a tick straddles"},
    {"_sofbuddy_tickpace_spin_ms", "2", "busy-wait when the tick is this close"},
    {"_sofbuddy_tracktime", "1", "compare client msec to server time"},
    {"_sofbuddy_tracktime_frames", "0", "usercmds measured"},
    {"_sofbuddy_tracktime_min", "30", "samples before a verdict"},
    {"_sofbuddy_tracktime_suspect", "0", "slots outside the tolerance"},
    {"_sofbuddy_tracktime_tolerance", "20", "allowed drift percent"},
    {"_sofbuddy_tracktime_window", "256", "samples kept per slot"},
    {"_sofbuddy_tracktime_worst_drift", "0", "worst drift percent among suspects"},
    {"_sofbuddy_ttt_enable", "0", "offer tic-tac-toe"},
    {"_sofbuddy_zpool", "1", "recycle small zone allocations"},
};

constexpr int kCvarInfoCount = static_cast<int>(sizeof(kCvarInfo) / sizeof(kCvarInfo[0]));
