// Host tests for src/features/clsv_pipe/clsv_logic.h (pure pipeline logic).
#include <cstdio>
#include <string>

#include "clsv_logic.h"

static int g_fails = 0;
#define CHECK(cond)                                                        \
    do {                                                                   \
        if (!(cond)) {                                                     \
            std::printf("FAIL %d: %s\n", __LINE__, #cond);                 \
            ++g_fails;                                                     \
        }                                                                  \
    } while (0)

static const char kDemoCfg[] =
    "//--- Generated by QuakeScriptParser ---//\n"
    "\n"
    "set f_f5e5_0 \"function clsv_welcome_init( )%0A{%0A  sp_sc_func_alias "
    "+clsv_hello clsv_hello%0A  echo %22hi%22%0A}\"\n"
    "sp_sc_cvar_unescape f_f5e5_0 f_f5e5_0\n"
    "\n"
    "set b_04f6_0 \"sp_sc_func_alias +itemuselean itemuselean; add ~t "
    "#itemuselean_delay\"\n"
    "sp_sc_cvar_unescape b_04f6_0 b_04f6_0\n"
    "\n"
    "// --- Entry Points ---\n"
    "sp_sc_func_load_cvar f_f5e5_0\n"
    "sp_sc_func_load_cvar b_04f6_0\n";

int main() {
    // Escape: structural bytes go %XX, parser triples pass through.
    {
        std::string out, err;
        CHECK(clsv::EscapeForSset("a b;c#d$e\tf", out, err));
        CHECK(out == "a%20b%3Bc%23d%24e%09f");
        CHECK(clsv::EscapeForSset("keep%20%22%0A", out, err));
        CHECK(out == "keep%20%22%0A");
        CHECK(!clsv::EscapeForSset("bad \"quote", out, err));
        CHECK(!clsv::EscapeForSset("bad\nnewline", out, err));
        CHECK(!clsv::EscapeForSset("bad\rcr", out, err));
        const std::string withNul("ab\0cd", 5);
        CHECK(!clsv::EscapeForSset(withNul, out, err));
    }

    // Parse: 2 chunks + 2 entries, unescape lines ignored.
    clsv::ClsvContent content;
    {
        std::string err;
        CHECK(clsv::ParseLoader(kDemoCfg, "welcome.cfg", 200, content, err));
        CHECK(content.names.size() == 2u);
        CHECK(content.names[0] == "f_f5e5_0");
        CHECK(content.names[1] == "b_04f6_0");
        CHECK(content.entries.size() == 2u);
        CHECK(content.entries[0] == "f_f5e5_0");
        CHECK(content.entries[1] == "b_04f6_0");
    }

    // Parse rejects: unknown lines, raw quotes, oversized chunks, empties.
    {
        clsv::ClsvContent c;
        std::string err;
        CHECK(!clsv::ParseLoader("echo hello\n", "x", 200, c, err));
        CHECK(!clsv::ParseLoader("set a \"b\"c\"d\"\n", "x", 200, c, err));
        CHECK(!clsv::ParseLoader("// nothing here\n", "x", 200, c, err));
        CHECK(!clsv::ParseLoader("set a \"has; semicolon and spaces ok\"\n", "x", 1, c, err));
    }

    // Plan order with 4 lanes: INFO, DATA 0/1, UNESC 0/1, LOAD 0/1, DONE.
    {
        clsv::ClsvConfig cfg;
        cfg.lanes = 4;
        cfg.perTick = 2;
        std::vector<clsv::ClsvSend> plan;
        std::string err;
        CHECK(clsv::BuildPlan(content, cfg, 7, plan, err));
        CHECK(plan.size() == 8u);  // 1 + 2 + 2 + 2 + 1
        CHECK(plan[0].cvar == clsv::kInfoCvar);
        CHECK(plan[0].text == "7");
        CHECK(plan[1].cvar == 0);
        CHECK(plan[1].text.compare(0, 13, "sset f_f5e5_0") == 0);
        CHECK(plan[1].text.find(' ') == 4);  // sset NAME <single token>
        CHECK(plan[1].text.find(';') == std::string::npos);
        CHECK(plan[1].text.find('#') == std::string::npos);
        CHECK(plan[1].text.find('\"') == std::string::npos);
        CHECK(plan[2].cvar == 1);
        // Continuous lane rotation across DATA + CMD phases.
        CHECK(plan[3].cvar == 2);
        CHECK(plan[3].text == "sp_sc_cvar_unescape f_f5e5_0 f_f5e5_0");
        CHECK(plan[4].cvar == 3);
        CHECK(plan[5].cvar == 0);
        CHECK(plan[5].text == "sp_sc_func_load_cvar f_f5e5_0");
        CHECK(plan[6].cvar == 1);
        CHECK(plan[7].cvar == clsv::kDoneCvar);
        CHECK(plan[7].text == "7");
        for (const auto& s : plan) {
            const std::string wire = clsv::FormatWire(s);
            CHECK(wire.size() <= clsv::kWireCap);
            CHECK(wire.compare(0, 4, "set ") == 0);
            CHECK(wire.back() == '\n');
            // Models StuffText_hook (spcl): this is what decides whether
            // the line reaches the client's Cbuf at all.
            CHECK(clsv::ClsvWirePassesSpclGate(wire));
        }
    }

    // Single lane: everything rotates through _sp_cl_sv_0.
    {
        clsv::ClsvConfig cfg;
        cfg.lanes = 1;
        std::vector<clsv::ClsvSend> plan;
        std::string err;
        CHECK(clsv::BuildPlan(content, cfg, 3, plan, err));
        CHECK(plan.size() == 8u);
        for (std::size_t i = 1; i + 1 < plan.size(); ++i)
            CHECK(plan[i].cvar == 0);
    }

    // Pacing: interval + perTick batching, first tick immediate.
    {
        clsv::ClsvConfig cfg;
        cfg.lanes = 4;
        cfg.perTick = 2;
        cfg.intervalFrames = 3;
        std::vector<clsv::ClsvSend> plan;
        std::string err;
        CHECK(clsv::BuildPlan(content, cfg, 1, plan, err));
        clsv::ClsvJob job;
        clsv::ClsvJobBegin(job, 1, plan, 100u);
        CHECK(job.phase == clsv::CLSV_SENDING);
        CHECK(clsv::ClsvBatchCount(job, cfg, 100u) == 2u);  // immediate
        job.pos += 2;
        job.lastTick = 100u;
        job.firstBatch = false;
        CHECK(clsv::ClsvBatchCount(job, cfg, 101u) == 0u);
        CHECK(clsv::ClsvBatchCount(job, cfg, 102u) == 0u);
        CHECK(clsv::ClsvBatchCount(job, cfg, 103u) == 2u);
        job.pos = plan.size();
        CHECK(clsv::ClsvBatchCount(job, cfg, 200u) == 0u);  // drained
        clsv::ClsvJobReset(job);
        CHECK(job.phase == clsv::CLSV_IDLE);
        CHECK(job.plan.empty());
    }

    // Sanitize clamps: lanes 1..90, perTick 1..12, chunk 32..240.
    {
        clsv::ClsvConfig c;
        c.lanes = 500;
        c.perTick = 0;
        c.maxEsc = 5;
        c.intervalFrames = 0;
        c = clsv::SanitizeConfig(c);
        CHECK(c.lanes == 90);
        CHECK(c.perTick == 1);
        CHECK(c.maxEsc == 32);
        CHECK(c.intervalFrames == 1);
    }

    // Wrap-safe linger clock (49.7-day GetTickCount wrap).
    {
        CHECK(clsv::ClsvElapsed(10u, 0xFFFFFFF0u, 25u));
        CHECK(!clsv::ClsvElapsed(10u, 0xFFFFFFF0u, 27u));
    }

    // spcl gate model: accept our shapes, reject everything the client
    // would print "SP Blocked server command" for.
    {
        CHECK(clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0 \"sset a b\"\n"));
        CHECK(clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_89 \"x\"\n"));
        CHECK(clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_98 \"7\"\n"));
        CHECK(clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_99 \"7\"\n"));
        // No raw %3B-style confusion: the gate sees chars, not escapes.
        CHECK(clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_1 \"a%3Bb%20c\"\n"));
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0 \"a;b\"\n"));   // ; anywhere
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0 \"a\"\n\n"));   // 2x \n
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0 \"a\nb\"\n"));  // inner \n
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0 \"a\""));       // no \n
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_100 \"a\"\n"));   // 3 digits
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_info \"a\"\n"));  // non-numeric
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_ \"a\"\n"));      // no digits
        CHECK(!clsv::ClsvWirePassesSpclGate("set _sp_cl_sv_0\"a\"\n"));      // no space
    }

    if (g_fails == 0)
        std::printf("clsv_logic: all checks passed\n");
    return g_fails == 0 ? 0 : 1;
}
