#!/usr/bin/env python3
"""Generate a pipe.func clsv_pipe listener for any lane count.

The listener parses nothing: every data arrival is exec'd verbatim and
counted (order comes from the reliable channel, DONE arrives last).
Only the lane registrations scale with --lanes; the logic is constant.
The file MUST be named pipe.func (or renamed consistently: spf_sc_addons
execs <basename>_init, so a rename needs the init function renamed too).

Usage:
    python3 clsv_gen_listener.py --lanes 4 -o pipe.func
    python3 clsv_gen_listener.py --lanes 90 -o pipe.func
"""
import argparse

HEADER = """//*******************************************
// pipe.func - clsv_pipe listener, client side (SoFplus addon) - GENERATED
//
// Generated by tools/clsv_gen_listener.py --lanes {lanes}. Do not edit by
// hand; regenerate instead. Wire protocol: see
// sof_buddy-server src/features/clsv_pipe/README.md.
//
// Auto-loaded by spf_sc_addons_init (sofplus/addons/*.func -> <basename>_init).
// Install: place at sofplus/addons/pipe.func and restart the client.
//

function pipe_init( )
{{
  set _pipe_got 0
  sp_sc_on_change _sp_cl_sv_98 pipe_on_info
{lanes_on}
  sp_sc_on_change _sp_cl_sv_99 pipe_on_done
  echo "pipe: listener ready ({lanes} lanes)"
}}

function pipe_on_info( * )
{{
  set _pipe_got 0
  echo "pipe: transfer started"
}}
"""

LANE_FN = """
function pipe_on_{lane}( * )
{{
  sp_sc_exec_cvar _sp_cl_sv_{lane}
  sp_sc_cvar_math_add _pipe_got 1
}}
"""

FOOTER = """
function pipe_on_done( * )
{
  echo "pipe: transfer complete, got #_pipe_got chunks"
  pipeack #_pipe_got
}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lanes", type=int, default=4,
                    help="data lanes _sp_cl_sv_0..N-1 (1..90)")
    ap.add_argument("-o", "--output", default="pipe.func",
                    help="output .func path (keep the pipe.func name for autoload)")
    args = ap.parse_args()
    if not 1 <= args.lanes <= 90:
        raise SystemExit("lanes must be 1..90")
    lanes_on = "\n".join(
        f"  sp_sc_on_change _sp_cl_sv_{i} pipe_on_{i}"
        for i in range(args.lanes)
    )
    out = HEADER.format(lanes=args.lanes, lanes_on=lanes_on)
    out += "".join(LANE_FN.format(lane=i) for i in range(args.lanes))
    out += FOOTER
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"Wrote {args.output} ({args.lanes} lanes)")


if __name__ == "__main__":
    main()
