#!/usr/bin/env python3
"""Emit generated_cmd_catalog.h from sofplus-cursor-rules command pages."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

EXTRAS = (
    "alias", "cmdlist", "echo", "exec", "gamemap", "map", "set", "status", "wait",
)

SKIP_STEMS = {"dot_COMMAND"}
SKIP_TOKS = {".", ""}


def tokens_from_mdc(path: Path) -> set[str]:
    names: set[str] = set()
    stem = path.stem
    if stem not in SKIP_STEMS and not stem.startswith("dot_"):
        names.add(stem)
    after = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("### "):
            after = True
            continue
        if not after:
            continue
        s = line.strip().strip("`")
        if not s:
            continue
        tok = s.split()[0].rstrip("`")
        if tok.startswith(".") or tok.startswith("sp_") or tok.startswith("sv_") or tok == stem:
            names.add(tok)
        break
    return names


def collect(rules: Path) -> list[str]:
    names: set[str] = set(EXTRAS)
    cmds = rules / ".cursor/rules/sofplus-api/commands"
    if cmds.is_dir():
        for p in cmds.glob("*.mdc"):
            names |= tokens_from_mdc(p)
    names -= SKIP_TOKS
    return sorted(names)


def emit(names: list[str]) -> str:
    lines = [
        "#pragma once",
        "// Auto-generated by tools/gen_cmd_catalog.py from sofplus-cursor-rules.",
        "namespace cmdcost {",
        f"constexpr int kCmdCount = {len(names)};",
        "inline const char* CmdName(int i) {",
        "    static const char* const k[] = {",
    ]
    for n in names:
        lines.append(f'        "{n}",')
    lines += [
        "    };",
        "    return (i >= 0 && i < kCmdCount) ? k[i] : \"?\";",
        "}",
        "}  // namespace cmdcost",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument(
        "--rules",
        default="",
        help="Path to sofplus-cursor-rules (commands live under .cursor/rules/sofplus-api/commands)",
    )
    args = ap.parse_args()
    rules = Path(args.rules) if args.rules else Path()
    names = collect(rules) if rules.is_dir() else list(EXTRAS)
    Path(args.output).write_text(emit(names), encoding="utf-8")
    print(f"cmd catalog: {len(names)} names -> {args.output}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
